### ISSUE TITLE
Scan reports No-Arg-Constructor of java.lang.Object as only method

### ISSUE THREAD

**Issue by KyleRogers** [buschmais/jqassistant#112]
If I execute

````
match
    (v)-[:DECLARES]->(m:Method) 
where
    v.fqn = "java.lang.Object"
return m,v2
````

I only get `<init>` as a result. What about `toString()`, `equals()` and `hashCode()` for example? Is this a bug or is it by design? And why?

**Comment by DirkMahler** [comment]
The java scanner plugin documentation contains a note explaining that referenced types which are not part of the scan are represented as :Type labeled nodes with a reduced set of properties and relations.
