### ISSUE TITLE
Handling of concepts without results

### ISSUE THREAD

**Issue by aparnachaudhary** [buschmais/jqassistant#120]
In the current implementation, if a concept yields no matching results a warning is logged on the console and HTML report highlights such concepts.

However, the resultset returned by concepts is not consistent. Some concepts like java:RuntimeException return _count_ of matching types while other concepts like jpa2:Entity return the matching type and/or its elements.

For concepts returning _count_ only; following check fails as the result contains a row with count as zero.

```java
if (conceptResult.getRows().isEmpty()) {
   console.warn("Concept '" + conceptResult.getRule().getId() + "' returned an empty result.");
}
```

How to solve this? One possibility is - always return count of matching types with/without other attributes and use this count for determining concepts with no results.

**Comment by DirkMahler** [comment]
Issue is related to #133.

**Comment by DirkMahler** [comment]
Result evaluation has been clarified in the code and documented:

- default strategy: row count
- optional: checking an aggregated value using an optionally specified column
