### ISSUE TITLE
Allow also scripts where currently cypher is used 

### ISSUE THREAD

**Issue by jensnerche** [buschmais/jqassistant#134]
Currently concepts and constraints contain a cypher query. Some concepts or constraints may be better written as a Groovy, JavaScript, ... script. The query should be enhanced or replaced by a script concept, e.g. <script lang="cypher">...</script> or <script lang="groovy">...</script>

**Comment by DirkMahler** [comment]
Script support has been implemented based on JSR-223 (Java Scripting API). Please verify if it fits your needs.
