### ISSUE TITLE
Build with M4 is slower than with M3

### ISSUE THREAD

**Issue by KyleRogers** [buschmais/jqassistant#141]
I tried to upgrade to M4 which was announced to have better scan performance but unfortunately the build is slower than before.

This is what I did: I built my project with ```mvn clean install``` afterwards I executed ```mvn  jqassistant:scan jqassistant:analyze``` 4 times dropping/ignoring the first build. I executed those steps for M3 and M4. Here are the results I got for my project:

M3: 28s, 29s, 28s
M4: 34s, 33s, 33s

As a main difference I realized, that jQAssistant made a looooong pause in M4 between those two lines in the log:

```
[info] Opening store in directory '/home/penndorf/workspaces/ebil-ws-client/client-parent/target/jqassistant/store'.
[info] [Type metadata {'FileDescriptor'}, Type metadata {'FileContainerDescriptor'}] use the same set of discriminators [File].
```

**Comment by KyleRogers** [comment]
Hi sorry for my late reply:

Checked with M3, M4 and RC-1 against the same project.

M3: 30s
M4: 27s
RC1: 23s

I don't see any pause while watching the log output anymore. Thanks a lot!

**Comment by DirkMahler** [comment]
Next release will show a (significant) improvment:
- upgraded to Neo4j 2.2 
- better caching of Maven plugin config
