### ISSUE TITLE
jqassistant.sh does not run under OS X

### ISSUE THREAD

**Issue by obfischer** [buschmais/jqassistant#153]
$ unset JQASSISTANT_HOME
    $ bash jqassistant.distribution-1.0.0-M4/bin/jqassistant.sh scan -f target
    readlink: illegal option -- f
usage: readlink [-n] [file ...]
Error: Unable to access jarfile /lib/jqassistant.scm.cli-1.0.0-M4.jar

Under OS X the `jqassistant.sh` does not run properly if `JQASSISTANT_HOME` is not set.

**Comment by toisrael** [comment]
@DirkMahler current solution from master works for me (tested with OS X 10.10.2 and CentOS 6)
