### ISSUE TITLE
Add the configured scan directory as offered path for plugins

### ISSUE THREAD

**Issue by jensnerche** [buschmais/jqassistant#156]
E.g. when configured the .git directory to be scanned, the directory itself is not offered to the plugin to be accepted. Instead all containing files and directories were given so that a small workaround is needed. The same for findbugs and checkstyle report dirs in standard maven and gradle layout: the files were all called main.xml and test.xml and cannot be distinguished, but the directory findbugs and checkstyle is the differentiating part.
Would be good to pass also the configured directories itself to the plugins.

**Comment by DirkMahler** [comment]
Plugins may check for so called scopes which by specified while scanning, e.g. from the command line:
```
jqassistant.sh scan -f git:repository::.git
```
