### ISSUE TITLE
Allow scanning of snapshots in Maven repositories

### ISSUE THREAD

**Issue by DirkMahler** [buschmais/jqassistant#171]
The current implementation of the Maven repository scanner allows incremental scanning of new artifacts which are never overwritten in the repository (i.e. releases). Snapshot may be updated, it shall be evaluated:

- if the index returned by Maven contains the snapshots
- how updates can be executed on the graph, e.g. by removing an existing artifact and all its sub-structures before scanning

**Comment by nachtgold** [comment]
You can insert a property to each element, which describes from which package and which version an element in the graph come from
