### ISSUE TITLE
Allow concepts not present in the code base

### ISSUE THREAD

**Issue by KyleRogers** [buschmais/jqassistant#197]
I'm trying to design a set of jqassistant rules that will be used/reused in multiple projects. Those rules express company-wide standards and coding rules. We want to fail the build if constraints defined in that rule set are violated. At the moment the build also fails if a concept is not matched. E.g. if I include a constraint using provided ```jpa2:Entity``` concept the build always fails if the project (e.g. a library) does not use JPA and thus doesn't have any entity.

Is there any possibility to fail the build if a constraint is violated but do NOT fail the build if certain concepts are not matched? Is this a valid use case or how would you solve the reused-rule-set problem?

I think this is related to the changes introduced in #120 und #133 but I don't understand the rationale behind the same behaviour for constraints and concepts.

**Comment by sebplorenz** [comment]
+1. I got the same problem with company wide rules that fail to apply the osgi concept on non-osgi projects.

**Comment by DirkMahler** [comment]
The idea behind this is to detect that a concept is not valid for a code base. This might happen for the following reasons:

- A technical concept (e.g. JPA entities) have been used in a project but a decision was taken to remove them. This means that constraints relying on this concept become invalid and might report false positives. So jQA rule set should be changed accordingly.
- The query for a concept is wrong, it should be detected as early as possible.

The default severity for concepts including "jpa2:Entity" is "INFO". You can configure the Maven plugin to fail on a higher severity:

```
  <failOnViolations>true</failOnViolations>
  <severity>major</severity>
```

**Comment by KyleRogers** [comment]
Sorry this does not work either - I've opened a ticket #198 to track this issue.

Additionally there is problem #199 which prevents me from reusing predefined constraints (e.g. package cycle constraint mentioned in #199). If severity could be overwritten for included concepts I could raise the fail-at-severity and include predefined constraints with a high enough severity (e.g. blocker). Otherwise I have to copy and duplicate predefined constraints and set a higher severity.
