### ISSUE TITLE
ServiceLoaderScanner can not handle inner class names

### ISSUE THREAD

**Issue by obfischer** [buschmais/jqassistant#215]
I have a project with inner classes implementing a SPI interface like this

   com.company.package.OuterClass$InnerClassImplementing

For such entries jQAssistant returns a node with the labels Java and Type but the fields fqn and name are empty.

**Comment by DirkMahler** [comment]
The existing test com.buschmais.jqassistant.plugin.java.test.scanner.ServiceLoaderIT has been extended to also verify inner classes but the described problem cannot be reproduced - can you provide further detail on the scenario?
