### ISSUE TITLE
Store is resetted after scan depending on maven project setup

### ISSUE THREAD

**Issue by slinstaedt** [buschmais/jqassistant#218]
Given the following maven project setup
```
myproject < myproject-parent
|- myproject-parent
|- myproject-module-1 < myproject-parent
|- myproject-module-2 < myproject-parent
```
where myproject-parent is the pom inheritance root of all other modules and `myproject` itself just hosts the build reactor, `jqassistant-maven-plugin` fails to reset it's store in the appropriate build reactor project. The store is opened in `myproject-parent`, because it is the first project in the build reactor, but the store is resetted in `myproject`.

As far as I nailed down this bug, store reset is tight to `MavenProject#isExecutionRoot()` which simple returns true for the invoked build reactor root, which in return may be the first module in the module, but depending on your project setup also may not.

**Comment by DirkMahler** [comment]
@slinstaedt I'd like to investigate that, can you provide a skeleton of such a multi-module maven project that shows the problem?

**Comment by slinstaedt** [comment]
Sure, but due to github file upload restrictions I had to provide an example project via dropbox [1].

[1] https://dl.dropboxusercontent.com/u/742124/myproject.tar.gz

**Comment by DirkMahler** [comment]
Thanks, will have a look at it.

**Comment by DirkMahler** [comment]
I could reproduce the problem locally and it seems that it can be fixed (quite easily).

Just one question: putting the parent into that location seems a bit strange to me - what's the intention behind it?

**Comment by slinstaedt** [comment]
My company has migrated from an Ant-based build to Maven recently. Due to the project size and having most of the developers working with eclipse the decision was made to use some kind of "flat project structure" [1]. From my experience this kind of project structure is not as uncommon as one might think.


[1] http://maven.apache.org/plugins/maven-eclipse-plugin/reactor.html

-- sent by phone

**Comment by DirkMahler** [comment]
Fix has been implemented and a test has been added.

Note: I think a better solution to map the hierarchical structure of Maven projects to the flat model of the Eclipse workspace is by reflecting the hierarchy in the artifactId like jQAssistant does:

- core
- core.store
- core.scanner
- core.report
- plugin
- plugin.java

What I find a bit confusing with the structure you provided is that the top level module (i.e. the reactor root) inherits from the parent which itself is included as a module.

**Comment by slinstaedt** [comment]
Yeah, I am aware of this discussion. We also had it a lot. Structuring maven project's like "each build reactor is also the inheritance parent of it's reactor child projects" is often easier to grasp than separate both concerns in different projects. Unfortunately I was not the one in charge to make this decision. 

But thanks for the fix. I will try it out on this quite large company's project, I am assigned to after my vacation.
