### ISSUE TITLE
jQA fails with message "Cannot read rules. The id of a rule must be unique: default(null)"

### ISSUE THREAD

**Issue by obfischer** [buschmais/jqassistant#228]
My current project fails with the following error message: 

    [ERROR] Failed to execute goal com.buschmais.jqassistant.scm:jqassistant-maven-plugin:1.0.0:analyze (analyze) on project uls-component-tests: Cannot read rules. The id of a rule must be unique: default(null) -> [Help 1]

I have two plugins with my custom constraints. All of my constraints in both plugins are added to the default group

    <group id="default">
        <includeConstraint refId="user-qa-rules:steckbrief:exists"/>
    </group>

    <group id="default">
        <includeConstraint refId="user-qa-rules:maven:all-dependencies-must-be-managed"/>
    </group>

Adding custom constraints to the default groups works only if you have one plugin which addes it constraints to _default_. If I add the second plugin jQA fails with the message above.

Actually this is not a serious problem but the error message does not help to detect this misconfiguration or error. 

Please improve the given error message or allow adding of constraints to the default group by multiple plugins.

**Comment by DirkMahler** [comment]
Restrictions on ids of rules have been implemented within #223 - error message will be enhanced to provide usable details to the user.
