### ISSUE TITLE
Wrong Result for Test Project

### ISSUE THREAD

**Issue by khmarbaise** [buschmais/jqassistant#239]
I have analyzed a [simple multi module project](https://github.com/khmarbaise/javaee/) and found a strange thing which i don't understand.

If i make the following cypher query:

```
MATCH (a:Artifact)-->()
WHERE a.type = 'test-jar'
RETURN a
```

i will get a list of artifacts which look like making a test-jar...but the whole project does not create a `test-jar`...a little bit more detailed:

```
MATCH (a:Artifact)-->()
WHERE a.type = 'test-jar'
RETURN
  DISTINCT a.name, a.group, a.type, a.fqn
```

| a.name | a.group | a.type | a.fqn |
| --- | --- | --- | --- |
| domain | com.soebes.examples.j2ee | test-jar | com.soebes.examples.j2ee:domain:test-jar:1.1.2-SNAPSHOT |
| service-client | com.soebes.examples.j2ee | test-jar | com.soebes.examples.j2ee:service-client:test-jar:1.1.2-SNAPSHOT |
| webgui | com.soebes.examples.j2ee | test-jar | com.soebes.examples.j2ee:webgui:test-jar:1.1.2-SNAPSHOT |
| service | com.soebes.examples.j2ee | test-jar | com.soebes.examples.j2ee:service:test-jar:1.1.2-SNAPSHOT |
| app | com.soebes.examples.j2ee | test-jar | com.soebes.examples.j2ee:app:test-jar:1.1.2-SNAPSHOT |
| appasm | com.soebes.examples.j2ee | test-jar | com.soebes.examples.j2ee:appasm:test-jar:1.1.2-SNAPSHOT |
| shade | com.soebes.examples.j2ee | test-jar | com.soebes.examples.j2ee:shade:test-jar:1.1.2-SNAPSHOT |
| parent | com.soebes.examples.j2ee | test-jar | com.soebes.examples.j2ee:parent:test-jar:1.1.2-SNAPSHOT |
| assembly | com.soebes.examples.j2ee | test-jar | com.soebes.examples.j2ee:assembly:test-jar:1.1.2-SNAPSHOT |

So the question is: Do i misunderstand the artifact or something else ? BTW: I have tested with 1.0.0

**Comment by DirkMahler** [comment]
The short answer: The result actually is wrong.

The long answer:

jQAssistant comes with a plugin which scans instances of "org.apache.maven.project.MavenProject" which are provided by the jQA Maven plugin. It's one of the very early implementations that have been created and therefore is quite a bit pragmatic assuming that there's always test code in a module - which is wrong. It needs to be fixed together with #229.

There are also things to be clarified about the data model itself: the plugin creates structures like

(m:Maven:Project)-[:CREATES]->(mainArtifact:Artifact:Directory)
(m:Maven:Project)-[:CREATES]->(testArtifact:Artifact:Directory)

Both (mainArtifact and testArtifact) have their type set to "jar" or "test-jar" which might be confusing as the nodes carry the label "Directory". Actually the directories are scanned but not the JAR artifacts themselves. The reason behind this is that the test classes shall always be present in the database (test-jars are only created if the maven-jar-plugin is configured to do it).

**Comment by khmarbaise** [comment]
Ok..Thanks for explanations...

**Comment by DirkMahler** [comment]
Just a hint - as you're only looking for nodes you can make your match class a bit shorter:

```
MATCH (a:Artifact)
WHERE a.type = 'test-jar'
RETURN a
```

**Comment by khmarbaise** [comment]
Sure, cause i don't rely on a relationship only on the Artifact itself...so `-->()' is not needed thanks.
