### ISSUE TITLE
Remove the wrong oss-parent

### ISSUE THREAD

**Issue by khmarbaise** [buschmais/jqassistant#245]
Based on the wrong configurations (hard coded versions of plugins) in oss-parent i would suggest to get the important content from there (distributionManagement, maven-gpg-plugin) and take over this information and maintain it yourself. Makes the configuration of the plugins simpler.

**Comment by khmarbaise** [comment]
May be we got an answer. I have created an appropriate [ticket for the problem in oss-parent](https://issues.sonatype.org/browse/OSSRH-17786).

**Comment by khmarbaise** [comment]
So after taken a look into [sonatypes github repo](https://github.com/sonatype/oss-parents) which stated it is no long maintained. The way is free to do the whole configuration on your own. If you like i could provide a PR for this.

**Comment by DirkMahler** [comment]
If this is not too much effort for you I would appreciate this very much... I would need to look up all the things which are needed.

**Comment by khmarbaise** [comment]
Unfortunately the final test of the configuration can only be done during the next release...
