### ISSUE TITLE
Don't generated folders in source area during integration tests.

### ISSUE THREAD

**Issue by khmarbaise** [buschmais/jqassistant#255]
If i ran the integration tests via `mvn clean verify -PIT` after the integration tests finished there is a folder generated `scm/neo4jserver/data/` which should be located into the appropriate `target` folder instead.

**Comment by khmarbaise** [comment]
The problem is that this folder is also created if i run the analyze/scan on a real project...

**Comment by DirkMahler** [comment]
That's an issue which comes from the embedded Neo4j server, see https://github.com/neo4j/neo4j/issues/4209. Will see if I can trigger that again.

**Comment by DirkMahler** [comment]
Neo4j 2.3 server creates a folder "neo4j-home" in the current working dir and stores SSL keys and certificates there. 
A workaround has been implemented to prevent this.
