### ISSUE TITLE
Wrong order of columns in the report XML

### ISSUE THREAD

**Issue by jensnerche** [buschmais/jqassistant#263]
In version 1.0.0. the order of the columns declared in the columns tag does not match the order of the columns in the  rows. Example:

      <result>
        <columns count="5">
          <column primary="true">complexity</column>
          <column>coveragethreshold</column>
          <column>coverage</column>
          <column>fqn</column>
          <column>signature</column>
        </columns>
        <rows count="5">
          <row>
            <column name="fqn">
              <value>net.sourceforge.plantuml.skin.rose.Rose</value>
            </column>
            <column name="coverage">
              <value>0</value>
            </column>
            <column name="complexity">
              <value>40</value>
            </column>
            <column name="coveragethreshold">
              <value>80</value>
            </column>
            <column name="signature">
              <value>net.sourceforge.plantuml.skin.Component createComponent(net.sourceforge.plantuml.skin.ComponentType,net.sourceforge.plantuml.skin.ArrowConfiguration,net.sourceforge.plantuml.ISkinParam,net.sourceforge.plantuml.cucadiagram.Display)</value>
            </column>
          </row>

Not a big deal because in the rows are names on the columns, but would be nice and make processing easier.

**Comment by obfischer** [comment]
Hi Jens, we will have a look at it.

**Comment by jensnerche** [comment]
Thanks! Maybe it fixes also another thing: the order of the columns in the maven output is not the order given in Cypher but (wrong) order in the XML report. If not, I'll file another issue. I give the order of the return parameters by intent and they occur randomly.
