### ISSUE TITLE
typo in documentation

### ISSUE THREAD

**Issue by rogergl** [buschmais/jqassistant#266]
There is a small typo in the manual regarding  'enforce names and locations of classes':

=> All controller implementations must be located in the package "model"

**Comment by DirkMahler** [comment]
Will review and correct this - Thanks!

**Comment by rogergl** [comment]
Seems there is another one:

    MATCH
               (package:PACKAGE)-[:CONTAINS]->(modelClass:Class:Model)
  .....

that doesn't work but

    MATCH
               (package:Package)-[:CONTAINS]->(modelClass:Class:Model)
  .....


does.

**Comment by DirkMahler** [comment]
Oh thanks for pointing that out! There has been a time when all labels have been upp case (e.g. PACKAGE), this has been changed to camel case (e.g. Package) - this example slipped through. Test should be added that examples are fully functional.
