### ISSUE TITLE
Schema location wrong ?

### ISSUE THREAD

**Issue by rogergl** [buschmais/jqassistant#267]
At least I get a 404 for this:

http://www.buschmais.com/jqassistant/core/analysis/rules/schema/v1.0

**Comment by obfischer** [comment]
Is a known issue we will fix with the next release.

**Comment by obfischer** [comment]
@DirkMahler can we use for this a subdomain we own? For example schema.jqassistang.org?

**Comment by DirkMahler** [comment]
Just clarifying this internally...

**Comment by obfischer** [comment]
Is a duplicate of #202. IT will be done for the 1.2.0 release.
