### ISSUE TITLE
question: check if package from test is in src ?

### ISSUE THREAD

**Issue by rogergl** [buschmais/jqassistant#268]
Is it possible to validate, that a package containing a test  at least exists in src ?

**Comment by DirkMahler** [comment]
It's possible to check the location of classes (main artifact or test code):

```
MATCH
  (project:Maven:Project)-[:CREATES]->(a:Artifact)-[:CONTAINS]->(t:Type)
WHERE
 a.type ="test-jar"
RETURN
 project.fqn, t.fqn
```

will return all test types. The main artifacts have the type "jar".

For further discussion I'd like to move this question to Stackoverflow or the Google group, is this ok for you?

**Comment by rogergl** [comment]
Sure, Stackoverflow is fine.

**Comment by DirkMahler** [comment]
Moved to http://stackoverflow.com/questions/32810848/validate-that-a-package-from-test-exists-in-src/
