### ISSUE TITLE
Better layout for reporting violations during the build

### ISSUE THREAD

**Issue by obfischer** [buschmais/jqassistant#280]
We would like to have a better visual separation for reporting violation constraints during a run of jQAssistant. This sould help the user to quickly identify each violation in the build log.

The proposed format is:

    ---[ Constraint Violation ]----------------------------------------------------
    Constraint: name.of.the.constraint
   
    THE DESCRITON PROVIDED BY THE VIOLATED CONSTRAINT.
  
    Result:
    variable1=value1 variable2=value2 variable3=value3
    variable1=value1 variable2=value2 variable3=value3
    -------------------------------------------------------------------------------
    <NEWLINE>

**Comment by obfischer** [comment]
Implemented but must be tested.

**Comment by DirkMahler** [comment]
Severity should be included in the message.

**Comment by obfischer** [comment]
I will finish it after the conference...
