### ISSUE TITLE
Testing 1.1.0-RC1

### ISSUE THREAD

**Issue by khmarbaise** [buschmais/jqassistant#281]
Hi, i'm trying to scan a project which ends with the following failure:

```
[ERROR] Failed to execute goal com.buschmais.jqassistant.scm:jqassistant-maven-plugin:1.1.0-RC1:scan (default) on project base-uti
l: Execution default of goal com.buschmais.jqassistant.scm:jqassistant-maven-plugin:1.1.0-RC1:scan failed: Unexpected problem whil
e scanning: item='MavenProject: coba.base.util:base-util:7.33.0-SNAPSHOT @ C:\xyz\pom.xml', pa
th='c:\xyz\pom.xml', scope='PROJECT', pipeline='[com.buschmais.jqassistant.plugin.maven3.impl.
scanner.MavenProjectScannerPlugin@1ec8991b]'. Unexpected problem while scanning: item='c:\xyz\
target\test-classes', path='c:\xyz\target\test-classes', scope='CLASSPATH', pipeline='[com.bus
chmais.jqassistant.plugin.java.impl.scanner.JavaClassesDirectoryScannerPlugin@15f6e73e]'. Unexpected problem while scanning: item=
'com.buschmais.jqassistant.plugin.common.impl.scanner.BufferedFileResource@4da484d4', path='/malencodedResourceBundles/media/syste
m/i18n/malencoded.properties', scope='CLASSPATH', pipeline='[com.buschmais.jqassistant.plugin.common.impl.scanner.FileResourceScan
nerPlugin@22b49404, com.buschmais.jqassistant.plugin.java.impl.scanner.PropertyFileScannerPlugin@69a681f4]'. Malformed \uxxxx encoding. -> [Help 1]
```

Scanning the same project except with release 1.0.0 it works...so looks like a regresssion in 1.1.0-RC1...

Any idea what can cause such problem?

**Comment by DirkMahler** [comment]
There has been a change in handling exceptions from scanner plugins from 1.0.0 to 1.1.0 - the idea is to detect implementation problems in plugins as early as possible.
It seems that you tried to scan a properties file containing an invalid unicode entity - thus reading the property file fails.
Such kind of error should be handled gracefully by the plugin but we should also consider adding an option to ignore such kind of (unexpected) errors and just issue warnings.

**Comment by DirkMahler** [comment]
The exception handling for the pluugin has been improved. Can you test with the latest snapshot (1.1.0-RC2-SNAPSHOT) or do you need a released version?

**Comment by khmarbaise** [comment]
I can do a test next week...

**Comment by DirkMahler** [comment]
1.1.0-RC2 is available from M2 central, try this one.
