### ISSUE TITLE
116MB Graph db created with 0 nodes

### ISSUE THREAD

**Issue by gavin834** [buschmais/jqassistant#285]
Scan of a simple Eclipse project created a graph db of total size 116MB, yet no data is returned for any query. Simple match(n) return count(n) returns 0.
Log of scan follows:

c:\jqa\1.1.0-RC2\bin\jqassistant.cmd scan -f . -s c:\jqa\playpen\httpAdaptor
Using JQASSISTANT_HOME 'C:\jQA\1.1.0-RC2\bin\..'.
[main] INFO com.buschmais.jqassistant.core.plugin.impl.PluginConfigurationReader
Impl - Loaded jQAssistant plugins [CDI, Common, Core Analysis, EJB3, GraphML, JA
X-RS, JPA 2, JUnit, Java, Java 8, Java EE 6, Maven 2 Repository, Maven 3, OSGi,
RDBMS, TestNG, Tycho, XML, YAML].
Opening store in directory 'c:\jqa\playpen\httpAdaptor'
[main] INFO com.buschmais.jqassistant.plugin.common.api.scanner.AbstractContaine
rScannerPlugin - Entering C:/Projects/EclipseWorkspace/focus-adaptor-http/.
[main] INFO com.buschmais.jqassistant.plugin.common.api.scanner.AbstractContaine
rScannerPlugin - Entering /target/focus-adaptor-http-0.0.1-SNAPSHOT-combined.jar

[main] INFO com.buschmais.jqassistant.plugin.common.api.scanner.AbstractContaine
rScannerPlugin - Leaving /target/focus-adaptor-http-0.0.1-SNAPSHOT-combined.jar
(3747 entries, 20676 ms)
[main] INFO com.buschmais.jqassistant.plugin.common.api.scanner.AbstractContaine
rScannerPlugin - Entering /target/focus-adaptor-http-0.0.1-SNAPSHOT-sources.jar
[main] INFO com.buschmais.jqassistant.plugin.common.api.scanner.AbstractContaine
rScannerPlugin - Leaving /target/focus-adaptor-http-0.0.1-SNAPSHOT-sources.jar (
20 entries, 13 ms)
[main] INFO com.buschmais.jqassistant.plugin.common.api.scanner.AbstractContaine
rScannerPlugin - Entering /target/focus-adaptor-http-0.0.1-SNAPSHOT.jar
[main] INFO com.buschmais.jqassistant.plugin.common.api.scanner.AbstractContaine
rScannerPlugin - Leaving /target/focus-adaptor-http-0.0.1-SNAPSHOT.jar (25 entri
es, 38 ms)
[main] INFO com.buschmais.jqassistant.plugin.common.api.scanner.AbstractContaine
rScannerPlugin - Leaving C:/Projects/EclipseWorkspace/focus-adaptor-http/. (200
entries, 21052 ms)

Maven details:
Apache Maven 3.1.1 (0728685237757ffbf44136acec0402957f723d9a; 2013-09-17 16:22:2
2+0100)
Maven home: c:\maven\apache-maven-3.1.1\bin\..
Java version: 1.8.0, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0\jre
Default locale: en_GB, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"

jqAssistant version:
jqassistant.distribution-1.1.0-RC2-20151021.121023-21-bin

**Comment by DirkMahler** [comment]
From the logs I can see that you scanned using the command line utility and that actually jar files have been found with entries

```
c:\jqa\1.1.0-RC2\bin\jqassistant.cmd scan -f . -s c:\jqa\playpen\httpAdaptor
...
[main] INFO com.buschmais.jqassistant.plugin.common.api.scanner.AbstractContaine
rScannerPlugin - Leaving /target/focus-adaptor-http-0.0.1-SNAPSHOT.jar (25 entri
es, 38 ms)
...
```

So there should be a database filled with information in the directory "c:\jqa\playpen\httpAdaptor". How did you start the server? Do you execute the CLI with the same -s option?

```
c:\jqa\1.1.0-RC2\bin\jqassistant.cmd server -s c:\jqa\playpen\httpAdaptor
```

**Comment by gavin834** [comment]
I didn't, but thought I saw in the output of the server command that it had picked up the correct store. That was wrong. What it picked up was a newly created jqassistant directory in the project directory. I don't know where that came from - but it's that that's empty.

When I re-run the server command with the correct store argument, I do indeed have data in the graph.

I'll try and make my noob errors in the google group rather than in erroneous bug reports.

**Comment by DirkMahler** [comment]
Sometime a user might not decide whether it's a bug or just a misuse - but in general it would be good to go for the Google group or SO first. But nevertheless hope you still enjoy playing with jQA :-)

Closing this issue.
