### ISSUE TITLE
Illegal State Exception scanning WAR file

### ISSUE THREAD

**Issue by gavin834** [buschmais/jqassistant#286]
Tried scanning a larger Eclipse web service project. Illegal State Exception thrown due to Neo4j Not Found Exception while scanning (combined) WAR file. We don't actually use the combined WAR file, so I tried again removing the combined WAR file; I got the same error on scanning the non-combined WAR file.

Console output follows:

c:\jqa\1.1.0-RC2\bin\jqassistant.cmd scan -f . -s c:\jqa\playpen\focus-graph-db-service
Using JQASSISTANT_HOME 'C:\jQA\1.1.0-RC2\bin\..'.
[main] INFO com.buschmais.jqassistant.core.plugin.impl.PluginConfigurationReader
Impl - Loaded jQAssistant plugins [CDI, Common, Core Analysis, EJB3, GraphML, JA
X-RS, JPA 2, JUnit, Java, Java 8, Java EE 6, Maven 2 Repository, Maven 3, OSGi,
RDBMS, TestNG, Tycho, XML, YAML].
Opening store in directory 'c:\jqa\playpen\focus-graph-db-service'
[main] INFO com.buschmais.xo.neo4j.impl.datastore.EmbeddedNeo4jDatastore - Creat
ing index for label Concept on property 'id'.
[main] INFO com.buschmais.xo.neo4j.impl.datastore.EmbeddedNeo4jDatastore - Creat
ing index for label Type on property 'fqn'.
[main] INFO com.buschmais.xo.neo4j.impl.datastore.EmbeddedNeo4jDatastore - Creat
ing index for label Artifact on property 'fqn'.
[main] INFO com.buschmais.xo.neo4j.impl.datastore.EmbeddedNeo4jDatastore - Creat
ing index for label Repository on property 'url'.
[main] INFO com.buschmais.xo.neo4j.impl.datastore.EmbeddedNeo4jDatastore - Creat
ing index for label Value on property 'value'.
[main] INFO com.buschmais.xo.neo4j.impl.datastore.EmbeddedNeo4jDatastore - Creat
ing index for label ColumnType on property 'databaseType'.
[main] INFO com.buschmais.xo.neo4j.impl.datastore.EmbeddedNeo4jDatastore - Creat
ing index for label Pom on property 'fqn'.
[main] INFO com.buschmais.xo.neo4j.impl.datastore.EmbeddedNeo4jDatastore - Creat
ing index for label Facelet on property 'fileName'.
[main] INFO com.buschmais.xo.neo4j.impl.datastore.EmbeddedNeo4jDatastore - Creat
ing index for label Package on property 'fqn'.
[main] INFO com.buschmais.xo.neo4j.impl.datastore.EmbeddedNeo4jDatastore - Creat
ing index for label Project on property 'fqn'.
[main] INFO com.buschmais.jqassistant.plugin.common.api.scanner.AbstractContaine
rScannerPlugin - Entering C:/Projects/Neo4jModellingWorkspace/focus-graph-db-ser
vice/.
[main] INFO com.buschmais.jqassistant.plugin.common.api.scanner.AbstractContaine
rScannerPlugin - Entering /target/focus-graph-db-service-sources.jar
[main] INFO com.buschmais.jqassistant.plugin.common.api.scanner.AbstractContaine
rScannerPlugin - Leaving /target/focus-graph-db-service-sources.jar (128 entries
, 298 ms)
[main] INFO com.buschmais.jqassistant.plugin.common.api.scanner.AbstractContaine
rScannerPlugin - Entering /target/focus-graph-db-service.war
[main] INFO com.buschmais.jqassistant.plugin.common.api.scanner.AbstractContaine
rScannerPlugin - Entering /WEB-INF/lib/aopalliance-1.0.jar
[main] INFO com.buschmais.jqassistant.plugin.common.api.scanner.AbstractContaine
rScannerPlugin - Leaving /WEB-INF/lib/aopalliance-1.0.jar (15 entries, 39 ms)
[main] INFO com.buschmais.jqassistant.plugin.common.api.scanner.AbstractContaine
rScannerPlugin - Entering /WEB-INF/lib/asm-1.0.2.jar
[main] INFO com.buschmais.jqassistant.plugin.common.api.scanner.AbstractContaine
rScannerPlugin - Leaving /WEB-INF/lib/asm-1.0.2.jar (51 entries, 516 ms)
[main] INFO com.buschmais.jqassistant.plugin.common.api.scanner.AbstractContaine
rScannerPlugin - Entering /WEB-INF/lib/asm-3.3.1.jar
[main] INFO com.buschmais.jqassistant.plugin.common.api.scanner.AbstractContaine
rScannerPlugin - Leaving /WEB-INF/lib/asm-3.3.1.jar (24 entries, 152 ms)
[main] INFO com.buschmais.jqassistant.plugin.common.api.scanner.AbstractContaine
rScannerPlugin - Entering /WEB-INF/lib/axis-1.4.jar
[main] INFO com.buschmais.jqassistant.plugin.common.api.scanner.AbstractContaine
rScannerPlugin - Leaving /WEB-INF/lib/axis-1.4.jar (842 entries, 4050 ms)
[main] INFO com.buschmais.jqassistant.plugin.common.api.scanner.AbstractContaine
rScannerPlugin - Entering /WEB-INF/lib/axis-jaxrpc-1.4.jar
[main] INFO com.buschmais.jqassistant.plugin.common.api.scanner.AbstractContaine
rScannerPlugin - Leaving /WEB-INF/lib/axis-jaxrpc-1.4.jar (1 entries, 8 ms)
[main] INFO com.buschmais.jqassistant.plugin.common.api.scanner.AbstractContaine
rScannerPlugin - Leaving /target/focus-graph-db-service.war (140 entries, 8258 m
s)
[main] INFO com.buschmais.jqassistant.plugin.common.api.scanner.AbstractContaine
rScannerPlugin - Leaving C:/Projects/Neo4jModellingWorkspace/focus-graph-db-serv
ice/. (885 entries, 11209 ms)
Exception in thread "main" java.lang.IllegalStateException: Unexpected problem w
hile scanning: item='.', path='C:\Projects\Neo4jModellingWorkspace\focus-graph-d
b-service\.', scope='NONE', pipeline='[com.buschmais.jqassistant.plugin.common.i
mpl.scanner.DirectoryScannerPlugin@440461ef]'.
        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerI
mpl.java:75)
        at com.buschmais.jqassistant.scm.cli.task.ScanTask.scan(ScanTask.java:12
6)
        at com.buschmais.jqassistant.scm.cli.task.ScanTask.executeTask(ScanTask.
java:73)
        at com.buschmais.jqassistant.scm.cli.task.AbstractTask.run(AbstractTask.
java:61)
        at com.buschmais.jqassistant.scm.cli.Main.executeTask(Main.java:235)
        at com.buschmais.jqassistant.scm.cli.Main.interpretCommandLine(Main.java
:187)
        at com.buschmais.jqassistant.scm.cli.Main.run(Main.java:73)
        at com.buschmais.jqassistant.scm.cli.Main.main(Main.java:44)
Caused by: java.lang.IllegalStateException: Unexpected problem while scanning: i
tem='com.buschmais.jqassistant.plugin.common.impl.scanner.BufferedFileResource@3
fecb076', path='/target/focus-graph-db-service.war', scope='NONE', pipeline='[co
m.buschmais.jqassistant.plugin.common.impl.scanner.FileResourceScannerPlugin@f4d
391c, com.buschmais.jqassistant.plugin.javaee6.impl.scanner.WebApplicationArchiv
eScannerPlugin@28269c65]'.
        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerI
mpl.java:75)
        at com.buschmais.jqassistant.plugin.common.api.scanner.AbstractContainer
ScannerPlugin.scan(AbstractContainerScannerPlugin.java:56)
        at com.buschmais.jqassistant.plugin.common.api.scanner.AbstractContainer
ScannerPlugin.scan(AbstractContainerScannerPlugin.java:31)
        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerI
mpl.java:67)
        ... 7 more
Caused by: java.lang.IllegalStateException: Unexpected problem while scanning: i
tem='java.util.zip.ZipFile@28e8dee7', path='/target/focus-graph-db-service.war',
 scope='WAR', pipeline='[com.buschmais.jqassistant.plugin.common.impl.scanner.Zi
pFileScannerPlugin@5020e5ab]'.
        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerI
mpl.java:75)
        at com.buschmais.jqassistant.plugin.common.api.scanner.AbstractArchiveSc
annerPlugin.scan(AbstractArchiveScannerPlugin.java:50)
        at com.buschmais.jqassistant.plugin.common.api.scanner.AbstractArchiveSc
annerPlugin.scan(AbstractArchiveScannerPlugin.java:21)
        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerI
mpl.java:67)
        ... 10 more
Caused by: java.lang.IllegalStateException: Unexpected problem while scanning: i
tem='com.buschmais.jqassistant.plugin.common.impl.scanner.ZipFileScannerPlugin$3
@2c9573f1', path='/WEB-INF/lib/axis-jaxrpc-1.4.jar', scope='WAR', pipeline='[com
.buschmais.jqassistant.plugin.common.impl.scanner.FileResourceScannerPlugin@f4d3
91c, com.buschmais.jqassistant.plugin.java.impl.scanner.JarScannerPlugin@64887fb
c]'.
        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerI
mpl.java:75)
        at com.buschmais.jqassistant.plugin.common.api.scanner.AbstractContainer
ScannerPlugin.scan(AbstractContainerScannerPlugin.java:56)
        at com.buschmais.jqassistant.plugin.common.api.scanner.AbstractContainer
ScannerPlugin.scan(AbstractContainerScannerPlugin.java:31)
        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerI
mpl.java:67)
        ... 13 more
Caused by: java.lang.IllegalStateException: Unexpected problem while scanning: i
tem='java.util.zip.ZipFile@4c18b432', path='/WEB-INF/lib/axis-jaxrpc-1.4.jar', s
cope='CLASSPATH', pipeline='[com.buschmais.jqassistant.plugin.common.impl.scanne
r.ZipFileScannerPlugin@5020e5ab]'.
        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerI
mpl.java:75)
        at com.buschmais.jqassistant.plugin.common.api.scanner.AbstractArchiveSc
annerPlugin.scan(AbstractArchiveScannerPlugin.java:50)
        at com.buschmais.jqassistant.plugin.common.api.scanner.AbstractArchiveSc
annerPlugin.scan(AbstractArchiveScannerPlugin.java:21)
        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerI
mpl.java:67)
        ... 16 more
Caused by: java.lang.IllegalStateException: Unexpected problem while scanning: i
tem='com.buschmais.jqassistant.plugin.common.impl.scanner.ZipFileScannerPlugin$3
@bec2d81', path='/META-INF/MANIFEST.MF', scope='CLASSPATH', pipeline='[com.busch
mais.jqassistant.plugin.common.impl.scanner.FileResourceScannerPlugin@f4d391c, c
om.buschmais.jqassistant.plugin.java.impl.scanner.ManifestFileScannerPlugin@2051
8250]'.
        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerI
mpl.java:75)
        at com.buschmais.jqassistant.plugin.common.api.scanner.AbstractContainer
ScannerPlugin.scan(AbstractContainerScannerPlugin.java:56)
        at com.buschmais.jqassistant.plugin.common.api.scanner.AbstractContainer
ScannerPlugin.scan(AbstractContainerScannerPlugin.java:31)
        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerI
mpl.java:67)
        ... 19 more
Caused by: org.neo4j.graphdb.NotFoundException: More than one relationship[DECLA
RES, OUTGOING] found for Node[1183]
        at org.neo4j.kernel.impl.core.NodeProxy.getSingleRelationship(NodeProxy.
java:265)
        at com.buschmais.xo.neo4j.impl.datastore.Neo4jRelationManager.getSingleR
elation(Neo4jRelationManager.java:85)
        at com.buschmais.xo.neo4j.impl.datastore.Neo4jRelationManager.getSingleR
elation(Neo4jRelationManager.java:20)
        at com.buschmais.xo.impl.EntityPropertyManager.createSingleReference(Ent
ityPropertyManager.java:172)
        at com.buschmais.xo.impl.EntityPropertyManager.createRelation(EntityProp
ertyManager.java:157)
        at com.buschmais.xo.impl.EntityPropertyManager.createEntityReference(Ent
ityPropertyManager.java:40)
        at com.buschmais.xo.impl.proxy.entity.property.EntityReferencePropertySe
tMethod.invoke(EntityReferencePropertySetMethod.java:15)
        at com.buschmais.xo.impl.proxy.AbstractProxyMethodService.invoke(Abstrac
tProxyMethodService.java:26)
        at com.buschmais.xo.impl.proxy.InstanceInvocationHandler.invoke(Instance
InvocationHandler.java:23)
        at com.sun.proxy.$Proxy108.setMainSection(Unknown Source)
        at com.buschmais.jqassistant.plugin.java.impl.scanner.ManifestFileScanne
rPlugin.scan(ManifestFileScannerPlugin.java:48)
        at com.buschmais.jqassistant.plugin.java.impl.scanner.ManifestFileScanne
rPlugin.scan(ManifestFileScannerPlugin.java:28)
        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerI
mpl.java:67)
        ... 22 more

Maven details:
Apache Maven 3.1.1 (0728685237757ffbf44136acec0402957f723d9a; 2013-09-17 16:22:2
2+0100)
Maven home: c:\maven\apache-maven-3.1.1\bin\..
Java version: 1.8.0, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0\jre
Default locale: en_GB, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"

jqAssistant version:
jqassistant.distribution-1.1.0-RC2-20151021.121023-21-bin

**Comment by louzadod** [comment]
In your case, is the root cause as below?

Caused by: java.lang.NullPointerException
	at com.buschmais.jqassistant.plugin.maven3.impl.scanner.MavenModelScannerPlugin.createMavenPomXmlDescriptor(MavenModelScannerPlugin.java:91)
	at com.buschmais.jqassistant.plugin.maven3.impl.scanner.MavenModelScannerPlugin.scan(MavenModelScannerPlugin.java:57)
	at com.buschmais.jqassistant.plugin.maven3.impl.scanner.MavenModelScannerPlugin.scan(MavenModelScannerPlugin.java:32)
	at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:77)
	... 19 more

**Comment by gavin834** [comment]
The full exception stack trace is in the error report, so no, I don't believe this is a NPE.
It looks to me like the root cause is this:

Caused by: org.neo4j.graphdb.NotFoundException: More than one relationship[DECLA
RES, OUTGOING] found for Node[1183]

**Comment by DirkMahler** [comment]
The manifest scanner stumbles on scanning /META-INF/MANIFEST.MF contained in "axis-jaxrpc-1.4.jar". Currently trying to reproduce the problem but without success...

 What happens if you scan the WAR file directly, i.e.

```
c:\jqa\1.1.0-RC2\bin\jqassistant.cmd scan -f /target/focus-graph-db-service.war -s c:\jqa\playpen\focus-graph-db-service
```
?

**Comment by gavin834** [comment]
Looks like the same error. I'm posting the complete output rather than just the exception in case it helps.


c:\jqa\1.1.0-RC2\bin\jqassistant.cmd scan -f target/focus-graph-db-service.war -s c:\jqa\playpen\focus-graph-db-service
Using JQASSISTANT_HOME 'C:\jQA\1.1.0-RC2\bin\..'.
[main] INFO com.buschmais.jqassistant.core.plugin.impl.PluginConfigurationReader
Impl - Loaded jQAssistant plugins [CDI, Common, Core Analysis, EJB3, GraphML, JA
X-RS, JPA 2, JUnit, Java, Java 8, Java EE 6, Maven 2 Repository, Maven 3, OSGi,
RDBMS, TestNG, Tycho, XML, YAML].
Opening store in directory 'c:\jqa\playpen\focus-graph-db-service'
[main] INFO com.buschmais.jqassistant.plugin.common.api.scanner.AbstractContaine
rScannerPlugin - Entering C:/Projects/Neo4jModellingWorkspace/focus-graph-db-ser
vice/target/focus-graph-db-service.war
[main] INFO com.buschmais.jqassistant.plugin.common.api.scanner.AbstractContaine
rScannerPlugin - Entering /WEB-INF/lib/aopalliance-1.0.jar
[main] INFO com.buschmais.jqassistant.plugin.common.api.scanner.AbstractContaine
rScannerPlugin - Leaving /WEB-INF/lib/aopalliance-1.0.jar (15 entries, 32 ms)
[main] INFO com.buschmais.jqassistant.plugin.common.api.scanner.AbstractContaine
rScannerPlugin - Entering /WEB-INF/lib/asm-1.0.2.jar
[main] INFO com.buschmais.jqassistant.plugin.common.api.scanner.AbstractContaine
rScannerPlugin - Leaving /WEB-INF/lib/asm-1.0.2.jar (51 entries, 365 ms)
[main] INFO com.buschmais.jqassistant.plugin.common.api.scanner.AbstractContaine
rScannerPlugin - Entering /WEB-INF/lib/asm-3.3.1.jar
[main] INFO com.buschmais.jqassistant.plugin.common.api.scanner.AbstractContaine
rScannerPlugin - Leaving /WEB-INF/lib/asm-3.3.1.jar (24 entries, 252 ms)
[main] INFO com.buschmais.jqassistant.plugin.common.api.scanner.AbstractContaine
rScannerPlugin - Entering /WEB-INF/lib/axis-1.4.jar
[main] INFO com.buschmais.jqassistant.plugin.common.api.scanner.AbstractContaine
rScannerPlugin - Leaving /WEB-INF/lib/axis-1.4.jar (842 entries, 3839 ms)
[main] INFO com.buschmais.jqassistant.plugin.common.api.scanner.AbstractContaine
rScannerPlugin - Entering /WEB-INF/lib/axis-jaxrpc-1.4.jar
[main] INFO com.buschmais.jqassistant.plugin.common.api.scanner.AbstractContaine
rScannerPlugin - Leaving /WEB-INF/lib/axis-jaxrpc-1.4.jar (1 entries, 1 ms)
[main] INFO com.buschmais.jqassistant.plugin.common.api.scanner.AbstractContaine
rScannerPlugin - Leaving C:/Projects/Neo4jModellingWorkspace/focus-graph-db-serv
ice/target/focus-graph-db-service.war (140 entries, 6755 ms)
Exception in thread "main" java.lang.IllegalStateException: Unexpected problem w
hile scanning: item='target\focus-graph-db-service.war', path='C:\Projects\Neo4j
ModellingWorkspace\focus-graph-db-service\target\focus-graph-db-service.war', sc
ope='NONE', pipeline='[com.buschmais.jqassistant.plugin.common.impl.scanner.File
ScannerPlugin@21ab919c]'.
        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerI
mpl.java:75)
        at com.buschmais.jqassistant.scm.cli.task.ScanTask.scan(ScanTask.java:12
6)
        at com.buschmais.jqassistant.scm.cli.task.ScanTask.executeTask(ScanTask.
java:73)
        at com.buschmais.jqassistant.scm.cli.task.AbstractTask.run(AbstractTask.
java:61)
        at com.buschmais.jqassistant.scm.cli.Main.executeTask(Main.java:235)
        at com.buschmais.jqassistant.scm.cli.Main.interpretCommandLine(Main.java
:187)
        at com.buschmais.jqassistant.scm.cli.Main.run(Main.java:73)
        at com.buschmais.jqassistant.scm.cli.Main.main(Main.java:44)
Caused by: java.lang.IllegalStateException: Unexpected problem while scanning: i
tem='com.buschmais.jqassistant.plugin.common.impl.scanner.FileScannerPlugin$1@7d
c92a06', path='C:/Projects/Neo4jModellingWorkspace/focus-graph-db-service/target
/focus-graph-db-service.war', scope='NONE', pipeline='[com.buschmais.jqassistant
.plugin.common.impl.scanner.FileResourceScannerPlugin@654db80b, com.buschmais.jq
assistant.plugin.javaee6.impl.scanner.WebApplicationArchiveScannerPlugin@282c507
5]'.
        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerI
mpl.java:75)
        at com.buschmais.jqassistant.plugin.common.impl.scanner.FileScannerPlugi
n.scan(FileScannerPlugin.java:50)
        at com.buschmais.jqassistant.plugin.common.impl.scanner.FileScannerPlugi
n.scan(FileScannerPlugin.java:20)
        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerI
mpl.java:67)
        ... 7 more
Caused by: java.lang.IllegalStateException: Unexpected problem while scanning: i
tem='java.util.zip.ZipFile@21ba0d33', path='C:/Projects/Neo4jModellingWorkspace/
focus-graph-db-service/target/focus-graph-db-service.war', scope='WAR', pipeline
='[com.buschmais.jqassistant.plugin.common.impl.scanner.ZipFileScannerPlugin@4fd
63c43]'.
        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerI
mpl.java:75)
        at com.buschmais.jqassistant.plugin.common.api.scanner.AbstractArchiveSc
annerPlugin.scan(AbstractArchiveScannerPlugin.java:50)
        at com.buschmais.jqassistant.plugin.common.api.scanner.AbstractArchiveSc
annerPlugin.scan(AbstractArchiveScannerPlugin.java:21)
        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerI
mpl.java:67)
        ... 10 more
Caused by: java.lang.IllegalStateException: Unexpected problem while scanning: i
tem='com.buschmais.jqassistant.plugin.common.impl.scanner.ZipFileScannerPlugin$3
@2139aa1f', path='/WEB-INF/lib/axis-jaxrpc-1.4.jar', scope='WAR', pipeline='[com
.buschmais.jqassistant.plugin.common.impl.scanner.FileResourceScannerPlugin@654d
b80b, com.buschmais.jqassistant.plugin.java.impl.scanner.JarScannerPlugin@336070
ab]'.
        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerI
mpl.java:75)
        at com.buschmais.jqassistant.plugin.common.api.scanner.AbstractContainer
ScannerPlugin.scan(AbstractContainerScannerPlugin.java:56)
        at com.buschmais.jqassistant.plugin.common.api.scanner.AbstractContainer
ScannerPlugin.scan(AbstractContainerScannerPlugin.java:31)
        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerI
mpl.java:67)
        ... 13 more
Caused by: java.lang.IllegalStateException: Unexpected problem while scanning: i
tem='java.util.zip.ZipFile@798ceea2', path='/WEB-INF/lib/axis-jaxrpc-1.4.jar', s
cope='CLASSPATH', pipeline='[com.buschmais.jqassistant.plugin.common.impl.scanne
r.ZipFileScannerPlugin@4fd63c43]'.
        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerI
mpl.java:75)
        at com.buschmais.jqassistant.plugin.common.api.scanner.AbstractArchiveSc
annerPlugin.scan(AbstractArchiveScannerPlugin.java:50)
        at com.buschmais.jqassistant.plugin.common.api.scanner.AbstractArchiveSc
annerPlugin.scan(AbstractArchiveScannerPlugin.java:21)
        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerI
mpl.java:67)
        ... 16 more
Caused by: java.lang.IllegalStateException: Unexpected problem while scanning: i
tem='com.buschmais.jqassistant.plugin.common.impl.scanner.ZipFileScannerPlugin$3
@6ca5720a', path='/META-INF/MANIFEST.MF', scope='CLASSPATH', pipeline='[com.busc
hmais.jqassistant.plugin.common.impl.scanner.FileResourceScannerPlugin@654db80b,
 com.buschmais.jqassistant.plugin.java.impl.scanner.ManifestFileScannerPlugin@20
a4cba7]'.
        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerI
mpl.java:75)
        at com.buschmais.jqassistant.plugin.common.api.scanner.AbstractContainer
ScannerPlugin.scan(AbstractContainerScannerPlugin.java:56)
        at com.buschmais.jqassistant.plugin.common.api.scanner.AbstractContainer
ScannerPlugin.scan(AbstractContainerScannerPlugin.java:31)
        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerI
mpl.java:67)
        ... 19 more
Caused by: org.neo4j.graphdb.NotFoundException: More than one relationship[DECLA
RES, OUTGOING] found for Node[59837]
        at org.neo4j.kernel.impl.core.NodeProxy.getSingleRelationship(NodeProxy.
java:265)
        at com.buschmais.xo.neo4j.impl.datastore.Neo4jRelationManager.getSingleR
elation(Neo4jRelationManager.java:85)
        at com.buschmais.xo.neo4j.impl.datastore.Neo4jRelationManager.getSingleR
elation(Neo4jRelationManager.java:20)
        at com.buschmais.xo.impl.EntityPropertyManager.createSingleReference(Ent
ityPropertyManager.java:172)
        at com.buschmais.xo.impl.EntityPropertyManager.createRelation(EntityProp
ertyManager.java:157)
        at com.buschmais.xo.impl.EntityPropertyManager.createEntityReference(Ent
ityPropertyManager.java:40)
        at com.buschmais.xo.impl.proxy.entity.property.EntityReferencePropertySe
tMethod.invoke(EntityReferencePropertySetMethod.java:15)
        at com.buschmais.xo.impl.proxy.AbstractProxyMethodService.invoke(Abstrac
tProxyMethodService.java:26)
        at com.buschmais.xo.impl.proxy.InstanceInvocationHandler.invoke(Instance
InvocationHandler.java:23)
        at com.sun.proxy.$Proxy124.setMainSection(Unknown Source)
        at com.buschmais.jqassistant.plugin.java.impl.scanner.ManifestFileScanne
rPlugin.scan(ManifestFileScannerPlugin.java:48)
        at com.buschmais.jqassistant.plugin.java.impl.scanner.ManifestFileScanne
rPlugin.scan(ManifestFileScannerPlugin.java:28)
        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerI
mpl.java:67)
        ... 22 more

**Comment by gavin834** [comment]
Don't know if this helps, but I isolated the JAR that was causing the exception (axis-jaxrpc-1.4.jar) and ran a scan on that single JAR. This scan completed without error. The scope & pipeline were of course different in this isolated scan, but there doesn't appear to be anything particularly wrong with the JAR in isolation.

**Comment by DirkMahler** [comment]
Yes, I've already it with the jar file and couldn't the problem? Did you try to scan only the WAR file (see above)?

**Comment by gavin834** [comment]
Yes, I did that yesterday. My comment immediately after your request to scan the WAR file shows the output. Looks like the same error. I included the entire console output in case there's anything in the output prior to the exception that gives any clues.

If I've misunderstood what you were looking for, let me know and I'll try to help.

**Comment by DirkMahler** [comment]
Do you see a chance to make this or a similar WAR file availble for us to track down the problem (i.e. by removing all the IP protected stuff and verifying the problem still exists?)

**Comment by gavin834** [comment]
I agree that would be a sensible next step, and I had been thinking about that. I haven't had time to prepare a stripped out build yet, but I'll see what I can do and get back to you.

**Comment by DirkMahler** [comment]
Good news - can reproduce the problem. Will investiage the cause now.
