### ISSUE TITLE
jQAssistant does not pick up additional rules from directory ./jqassistant

### ISSUE THREAD

**Issue by obfischer** [buschmais/jqassistant#293]
Given Maven based build which uses the Maven plugin of jQAssistant to performe some validations. The rules for the constraints to check are provided in form of analyzer plugin (package as a Jar and attached as dependency of the Maven plugin.

There also some rules provided in a file `rules.xml` in the subdirectory `./jqassistant`.

None of these rules will be executed while analysing the project.

The exepected behaviour is that all rules found in `./jqassistant` will be executed too.

**Comment by obfischer** [comment]
I started Maven with `-X` and found the following debug message the output:

    [INFO] Executing analysis for 'XXX'.
    [INFO] Reading rules from directory /Users/.../.../XXX/jqassistant
    [DEBUG] Adding rules from file /Users/.../.../XXX/jqassistant/rules.xml
    [DEBUG] Reading rules from '/Users/.../.../XXX/jqassistant/rules.xml'.

That means that the rules file is found by jQAssistant.

**Comment by obfischer** [comment]
The Maven goal `available-rules` lists all rules including the rules in `./jqassistant` while the result of `effective-rules` is always:

    [INFO] --- jqassistant-maven-plugin:1.1.0-RC3-SNAPSHOT:effective-rules (default-cli) @ XXX ---
    [INFO] Loaded jQAssistant plugins [Common, Core Analysis, JUnit, Java, Maven 3, XML].
    [INFO] Opening store in directory '/Users/obf/epost/eml-service/jqassistant.datastore'.
    [INFO] Effective rules for 'emailservice'.
    [INFO] Reading rules from directory /Users/obf/epost/eml-service/jqassistant
    [INFO] Groups [0]
    [INFO] Constraints [0]
    [INFO] Concepts [0]
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD SUCCESS
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 2.923 s
    [INFO] Finished at: 2015-11-09T23:48:15+01:00
    [INFO] Final Memory: 33M/550M
    [INFO] ------------------------------------------------------------------------

**Comment by DirkMahler** [comment]
Are these additional rules referenced in any group? If yes it's necessary to activate this group either by 

- including it in the default group
- adding it to the plugin configuration
- running mvn with the command line parameter -Djqasstant.groups=MyGroup (works for the analyze and effective-rules goals)

**Comment by obfischer** [comment]
After speaking about this issue it turned out that jQAssistant works as designed. The automatic pickup of rules in `./jqassistant`works only if you use the default group and if you don't specify a list of rule groups in the POM as I did it.
