### ISSUE TITLE
Error while scanning icu4j-2.6.1.jar

### ISSUE THREAD

**Issue by DirkMahler** [buschmais/jqassistant#301]
While scanning the file icu4j-2.6.1.jar the following error is reported:

```
java.lang.ArrayIndexOutOfBoundsException: 48188
at org.objectweb.asm.ClassReader.readClass(Unknown Source)
at org.objectweb.asm.ClassReader.accept(Unknown Source)
at org.objectweb.asm.ClassReader.accept(Unknown Source)
```  

It seems that the class 'com.ibm.icu.impl.data.LocaleElements_zh__PINYIN' has a format that cannot be handled by ASM.

**Comment by obfischer** [comment]
Just had a look at the InvalidDescriptor. May we should call ist ValidityDescriptor with an property valid? I might be easier to use valid=true in an query instead of invalid=true. WDYT?

**Comment by DirkMahler** [comment]
Intention was to set the property only if a problem was found, i.e. to save a bit of disk space and allow queries like that:

```
match (f:Type:File) where has(f.invalid) return f
```

The other around would be:

```
match (f:Type:File) where not has(f.valid) return f
```

Not sure which is better...

**Comment by obfischer** [comment]
For the sake of the user it would be IMHO better to avoid to use negations. Even if it costs more disk space. WDYT?

**Comment by DirkMahler** [comment]
Negations are a bad thing - at least I learned this at the university... I agree that it's more intuitive to use valid over invalid but probably we should find another name for this property: 

What does it mean that a file is valid?

In our case it's only an information that the file could be scanned.

**Comment by obfischer** [comment]
For me it means that we have been able to read and 'understand' the whole artifact (file) without any problems from the view of the responsible scanner.
