### ISSUE TITLE
Provide effective model for Maven Project nodes

### ISSUE THREAD

**Issue by DirkMahler** [buschmais/jqassistant#309]
The Maven plugin provides a relation HAS_MODEL which points to the raw model of a pom.xml file as it has been parsed.
There should also be a relation HAS_EFFECTIVE_MODEL to the interpolated model as resolved by Maven.

**Comment by obfischer** [comment]
Oh, it is already implemented? Great!

**Comment by obfischer** [comment]
Just executed `MATCH (n:Maven)-[:HAS_EFFECTIVE_MODEL]->(o:Maven) RETURN n, o` on a database created from the current master branch. This query didn't returned anything.

**Comment by DirkMahler** [comment]
There's an IT in the Maven plugin verifying this and AFAIK it's passing: https://github.com/buschmais/jqassistant/tree/master/scm/jqassistant-maven-plugin/src/it/singlemodule/model

**Comment by obfischer** [comment]
Sorry, my fault. It is ok.
