### ISSUE TITLE
Maven aggregation goals not executed if reactor contains skipped modules

### ISSUE THREAD

**Issue by DirkMahler** [buschmais/jqassistant#310]
- A Maven reactor contains two modules A and B and a parent which defines executions for the scan and analyze goal
- B depends on A
- A has the property "jqassistant.skip" set to prevent scanning

In this case the analyze goal is not executed at the end of B

**Comment by obfischer** [comment]
Would it be an solution to set `jqassistant.skip` to false?

**Comment by DirkMahler** [comment]
No: the analyze mojo (and all other aggregators) checks if all modules for the current projects have been executed and will run if this is true.
The activated skip property in A causes wrong "counting" (i.e. house-keeping) of already executed modules - if a module is skipped it must still be taken into account for checking if the aggregation can be performed.
