### ISSUE TITLE
uniqueness in concepts (and scanners)

### ISSUE THREAD

**Issue by aklemp** [buschmais/jqassistant#312]
Hi,

I already discussed uniqueness of types created by the scanners on http://stackoverflow.com/questions/33940842/multiple-jars-with-unique-types. Now I think, this is actually unwanted behavior. The concept `dependency:Artifact` is supposed to `MERGE` relationships and add a `used` property. However, I have Maven artifacts with a `scope` property on a `DEPENDS_ON` relationship. Running the dependency concept leads to a second `DEPENDS_ON` with the `used` property. The merge is working (not creating a new relationship) when not specifying a property. Thus, a simple query like `-[:DEPENDS_ON{scope:x,used:y}]->` is not working. I'm not sure if this is a bug in Cypher/Neo4j because `MERGE` should actually merge. The existing jQAssistant concepts and maybe also the scanners should be reviewed for problems like this.

As workaround, the following seems to merge a relationship (optionally creating it) and add a property (or overwriting it).

```
MERGE
  (a1)-[x:DEPENDS_ON]->(a2)
SET
  x.used = true
```

I don't think, such complex graphs with redundant nodes and relationships improve usability because all constraints and custom concepts have to expect multiple relations and nodes. They would be hard to understand and maintain.

I like the overall approach of jQAssistant and I could probably spare some time to help if you also think, the generated graphs should be simpler.

Kind regards,
  aklemp

**Comment by DirkMahler** [comment]
I agree that we should keep the graphs as simple as possible - but it's also necessary that they are correct. 
The mentioned concept is one of the oldest in the code base and it's very likely that the outcome of it hasn't been defined clearly enough. I agree with expected behavior you're describing and it will be changed accordingly.

**Comment by aklemp** [comment]
Yes, the combination of simple and correct would be perfect. :-) Incorrect graphs are even worse than complex ones...

**Comment by DirkMahler** [comment]
The merge pattern has been changed to the proposal which IMHO is correct and a test has been extended to verify the expected behavior.
