### ISSUE TITLE
change default severity

### ISSUE THREAD

**Issue by aklemp** [buschmais/jqassistant#313]
Hi,

it seems that the default severity is not useful, as I understand it. Constraints by default have INFO and concepts have MINOR (in your plugins). That means when I set the severity in Maven to MINOR, the build is successful when a constraint fails but not if a concept fails. In my opinion, a concept like detecting JPA entities should be optional but a constraint checking that entities are in specific packages is mandatory. If no types are labeled as entity, the constraint is not failing, because there are no entities. At least there are no false positives.

I propose, that concepts stay at MINOR and constraints are raised to MAJOR. The metrics constraints can be left at INFO, because they are only useful in reports. Then the user can configure the behavior easily in Maven without having to specify severities for all included concepts and constraints.

Kind regards,
  aklemp

**Comment by DirkMahler** [comment]
Implemented in 1.3.0
