### ISSUE TITLE
Store location ...

### ISSUE THREAD

**Issue by chrisdutz** [buschmais/jqassistant#315]
Currently it seems the plugin opens a store in the parent or the module where the plugin is defined. Usually this isn't a problem. In my current project however the reactor parent != the maven parent. As long as the parent project is still part of the reactor, everything is ok, but as soon as the parent isn't part of the reactor it seems jqassistant opens a store in every module and fails with an out of memory exception. If I give it more ram, it just fails later ... I haven't managed to get all building to see if the generated reports are still valid. 

It would be good if the location for the store would be the reactor parent and not the "maven parent".

Chris

**Comment by DirkMahler** [comment]
The jQA Maven plugin uses the notion of a root module, see http://buschmais.github.io/jqassistant/doc/1.1.0/#ProjectScope
The store should be located in the target directory of that root module - is this the case for you?

**Comment by obfischer** [comment]
@chrisdutz Have you seen the option to specify the store directory in the configuration of the maven plugin?

**Comment by obfischer** [comment]
Where is the different for you between the Maven and the reactor parent? Do you mean the Parent POM of your project by "Maven parent"?

**Comment by chrisdutz** [comment]
Sorry for the late response ... seem I don't get email notifications :-(

Well the root sort of depends on the view :-) ... in Maven I have a root when looking at the parent relation and one when looking at the reactor. Currently it uses the parent relation. In my case for example I have someting like this:

- company-parent:pom
- ractor:pom
-- module A - reactor: pom
--- module A - API: jar
--- module B - IMPL: jar
-- module B - reactor: pom
--- module B - API: jar
--- module B - IMPL: jar

each API and IMPL has their matching reactor as parent, and the module reactors have "company-parent" as parent (not the "reacor" itself). If company-parent is not part of the build I couldn't really create useable output at all. so it seems the graphml plugin creates output in the "reactor" project, while the rest seems to place everything in the "company-parent" module. I think it should place everything in the "reactor" directory instead.

**Comment by chrisdutz** [comment]
Any update on this? Actually this issue is rather important for me. I can user JQAssistant locally just fine as I have all the projects in my build (including the company-parent), but most people here don't they just rely on it being downloaded. So all of these will have problems.

**Comment by DirkMahler** [comment]
Hi Christofer, will try to reproduce it until tomorrow and come back with an explanation.

**Comment by DirkMahler** [comment]
At which level do you specify the jQA maven plugin?

**Comment by chrisdutz** [comment]
Well in above example the plugin is defined in the company-parent.pom ... this is also where ... hmm ... aaargh ... ok ... I think I know what's the problem.

Because the rules are located in the company-parent they are evaluated there. I should try to move the rules to the reactor reactor.pom project ... would this work?

**Comment by DirkMahler** [comment]
Hm, I think not - as your reactor is not a parent of your modules. Will try if I can give you a quick solution for this.

**Comment by chrisdutz** [comment]
What would be cool, if the location would be (if not explicitly defined) in the reactor root as we can be sure this directory exists. Regarding the rules ... would it be possible to create a rule-jar and have the plugin config depend on that jar and read the rules from there.
So it would be something like this:

- company-rules: jar
- company-parent:pom (defines jqa plugin and references rules form company-rules:jar)
- ractor:pom (has no parent)
-- module A - reactor: pom (parent is company-parent)
--- module A - API: jar (parent is module A - reactor)
--- module B - IMPL: jar (parent is module A - reactor)
-- module B - reactor: pom (parent is company-parent)
--- module B - API: jar (parent is module B - reactor)
--- module B - IMPL: jar (parent is module B - reactor)

**Comment by DirkMahler** [comment]
These are exactly the same directions which I was thinking about:

1. It is already possible to put rules into jar files and add them as dependency to the jqassistant-maven-plugin, see 
http://buschmais.github.io/jqassistant/doc/1.1.1/#_custom_rule_plugin and http://buschmais.github.io/jqassistant/doc/1.1.1/#_using_custom_plugins 

This should already work if you want to provide rules from the company-rules level

2. If you need to provide rules on reactor level then you give the Maven plugin a configuration parameter "rulesDirectory" (-Djqassistant.rules.directory) which will be used, similar to "storeLocation" (-Djqassistant.store.location). This will make it possible for you to make things running but it won't look fine.
But I was also thinking about giving jQA a setting "use module x.yz. as root module of a project" or "use the execution/reactor as root of a project) to lookup rules and place the store. This could be an option for an upcoming release (e.g. 1.1.3) and shouldn't be difficult to implement.

**Comment by DirkMahler** [comment]
@chrisdutz Is it ok for you to close this issue?
