### ISSUE TITLE
question about CDI constraints

### ISSUE THREAD

**Issue by aklemp** [buschmais/jqassistant#316]
Hi,

there are the constraints `cdi:BeansMustNotUseFieldInjection` and `cdi:BeansMustUseConstructorInjection`. The former is effectively contained in the latter. However, what is your rationale, disallowing field injection or even allowing only constructor injection? I see that setter methods can implement some logic on injection and constructor injection allows immutable classes. From my experience, injection is mostly used for glueing things together without any specific logic. Are there other advantages that I'm not aware of?

Kind regards,
  aklemp

**Comment by DirkMahler** [comment]
"Field injection is evil". There is a blog post on our project's homepage giving some background on it, see http://jqassistant.org/context-dependency-injection-are-you-doing-it-right/.
It references a post by Oliver Gierke being even a bit more clear on the subject: http://olivergierke.de/2013/11/why-field-injection-is-evil/

**Comment by aklemp** [comment]
Thank you for the links.
