### ISSUE TITLE
severity on groups

### ISSUE THREAD

**Issue by aklemp** [buschmais/jqassistant#317]
Hi,

when organizing my rules in groups, I was thinking about defining a common severity for them. Unfortunately, this is not possible right now. It could be defined on a group and/or when including that group in another group. It would be a nice convenience enhancement. What do you think?

Kind regards,
  aklemp

**Comment by DirkMahler** [comment]
What would be the expected behavior? My expectation would be: If a severity is defined for a group then all rules included in this group (i.e. concepts, constraints, groups) will use this severity. Do you agree?

**Comment by aklemp** [comment]
I agree. That way, the outermost severity wins and thus, severities defined in plugins can be overriden in a specific project.

**Comment by DirkMahler** [comment]
Severity for groups has been implemented, see examples in https://github.com/buschmais/jqassistant/blob/1.1/core/analysis/src/test/resources/severity.adoc and https://github.com/buschmais/jqassistant/blob/1.1/core/analysis/src/test/resources/severity.xml
