### ISSUE TITLE
Potential bug in the documentation for the graphml plugin?

### ISSUE THREAD

**Issue by chrisdutz** [buschmais/jqassistant#326]
I am currently experimenting with the graphml plugin and noticed that in the documentation where "virtual relations" are discussed, the virtual relation is defined as:
```
{role: "relationship", type:"DEPENDS_ON", startNode:startNode(p1), endNode:endNode(p2)}
```
I think the "startNode(p1)" should be "p1" and "startNode(p2)" should simply be "p2" as both p1 and p2 should be nodes from my understanding. At least when adopting this pattern the plugin is complaning that it requires p1 and p2 to be relations and not nodes.

**Comment by DirkMahler** [comment]
Confirmed - it's wrong.
