### ISSUE TITLE
Plugin mechanism for post-processing (graphml) output

### ISSUE THREAD

**Issue by chrisdutz** [buschmais/jqassistant#336]
Hi,

I am currently trying to implement some functionality to post-process generated graphml documents. In general I am trying to have the nodes layouted. Instead of implementing a maven-plugin for this to run after jQAssistant, I would like to have it run inside jQAssistant. Here I was thinking of a plugin for the graphml plugin. 

If the graphml plugin would define an interface for post processing and a config option for a post-processor(-chain). This would be great. 

I am currently thinking of two plugins for this:
- XSLT post processor
- GraphML layout post processor.

What do you  think? Would be happy to help out implementing this feature.

Chris

**Comment by chrisdutz** [comment]
Ok ... so no update on this ... so I'll start working on something like this ... would have been cool though  I someone could have helped me in getting started with this.

**Comment by DirkMahler** [comment]
Sorry, there were too many things to do during last weeks...

In general I think it could make sense to provide post-processing capabilities - the question for me is if this means creating a plugin mechanism for plugin. Do you already have something special in mind?
