### ISSUE TITLE
SONAR integration broken

### ISSUE THREAD

**Issue by rzozmann** [buschmais/jqassistant#338]
In a (fresh) installation of SonarQube 5.1.2 with jQAssistant 1.1.1 plugin i cannot export the rules for a Maven based jqassistant analyze-goal. I followed the instructions from manual to configure maven POM for my project and the quality profile in SONAR. Extending the permalink from SONAR by the 'format=jqassistant' parameter results in a error. Entering the rulesUrl (like *http://localhost:9000/profiles/export?format=jqassistant&language=java&name=MySonarProfile*) in Browser gives me a:
> Unknown quality profile exporter: jqassistant

**Comment by DirkMahler** [comment]
Can reproduce it with Sonar 5.1.1 - the rules can be managed but not exported via permalinks. Need to investigate what has changed there.

**Comment by rzozmann** [comment]
Hi Dirk,

i spend more time to inspect the problem. I give you a pull request with changes to fix the incompatibility. The key for the export problem seems to be the missed value of 'supported languages' (aka 'Java') in JQAssistantProfileExporter. My pull request will not solve all deprecations in API/Code.

Before doing more i want to discuss the your further plans around SONAR integration.
Do you have concrete plans to extend jQAssistant in a way related to the SONAR integration?

My company is interested on jQAssistant, but we work with SONAR as our central QA tool. Internal discussions revealed some requirements to use jQAssistant in our projects. From the tooling aspect: we need to have import rules (concepts+constraints) on a peer project base, changeable by the project owner. Rules strongly depends on technology and other project related aspects and cannot be defined on meta level (generic way) detailed enough. So our (current) approach is:
1. Defining rules on local projects, so we can test the effect
2. Upload tested XML (or AsciiDoc) to SONAR sever for the specific project (configuring 'group', enablement etc.) and running jqassistant as part of our daily QA builds

Implementing that approach should be either supported by jQAssistant out-of-the-box (extending the sonar plugin) or compatible (by API) to the sonar plugin.
That's the reason i want to get more informations about the plans with the SONAR integration....

Regards
Ralf

**Comment by DirkMahler** [comment]
In general integration with other tools is always quite high effort (i.e. Maven and SonarQube) and resources are restricted. Thus development in general is driven by user demands - in the last time the focus on the SonarQube integration has been quite low as there were only very few requests for it.

I can follow your approach and it makes sense to me. It needs to be evaluated if it actually works in the end - I've already tried to create an importer for jQA rules into SonarQube but didn't find out how I can do that dynamically. Do you have any hints?
