### ISSUE TITLE
Add name of source file to java types

### ISSUE THREAD

**Issue by DirkMahler** [buschmais/jqassistant#341]
A scanned Java class file shall have an attribute "sourceFileName" that represents the name of the source file it has been compiled from.

**Comment by obfischer** [comment]
It is somehow possible to get the full path of the source file?

**Comment by DirkMahler** [comment]
Not directly - but if the context is known (e.g. Maven Project) it could be inferred. Thinking about a resolver approach to create nodes for source files, this would also allow correlation with other plugins (e.g. Git).
