### ISSUE TITLE
Wrong severity in report file

### ISSUE THREAD

**Issue by rzozmann** [buschmais/jqassistant#344]
I have custom rules defined in /jqassistant as XML like:
> \<constraint id="foo" severity="critical">
>   ...
> \</constraint>

In the resulting jqassistant-report file the severity is always set to `<severity level="4">info</severity>` (the internal default?!)

Version: 1.1.3-SNAPSHOT (1.1.1 branch)

**Comment by rzozmann** [comment]
Now i have seen while analysing: `Validating constraint 'foo' with severity: 'INFO (from CRITICAL)'.`
But why is the effective severity reduced to INFO?

**Comment by DirkMahler** [comment]
This means that a group exists which includes the constraint and overrides its default severity (which has been critical). In case of XML rules it would look like:

```
<includeConstraint refId="foo" severity="INFO" />
```

**Comment by rzozmann** [comment]
I didn't know that a includeConstraint/includeConcept statement in group can have a severity.
- The documentation should be improved to explain that :-)
- If a `includeConstraint` always have a severity (custom or default) overwriting the severity on rule definition, makes the severity declaration on the rule useless?!

The severity value on includeXYZ is case sensitive. Using INFO (instead of 'info') will break the build with something like:
> [ERROR] ...:jqassistant-maven-plugin:1.1.2:analyze failed: Cannot read rules from '/*.xml'. UnmarshalException: cvc-enumeration-valid: Wert 'MAJOR' ist nicht Facet-gültig in Bezug auf Enumeration '[blocker, critical, major, minor, info]'. Er muss ein Wert aus der Enumeration sein. -> [Help 1]

**Comment by obfischer** [comment]
On the comment relating to the `serverity` attribute. Implementing #202 would or could help to avoid suche problems. IMHO.

**Comment by DirkMahler** [comment]
- Documentation about handling of severities has been enhanced for #317.
- Case sensitivity comes from the fact that they are specified as enum constants in the XML schema which shall be provided online (see last comment of obfischer)
