### ISSUE TITLE
Missing concept listing in the GraphML report plugin documentation

### ISSUE THREAD

**Issue by obfischer** [buschmais/jqassistant#347]
The example `reports.xml` for the GraphML report plugin at http://buschmais.github.io/jqassistant/doc/1.1.2/#_graphml refers to a not listed concept called `dependency:Package`.

We should also provide this concept to help users of jQAssistant to be able to use the example without any modification via copy and paste.

**Comment by DirkMahler** [comment]
"dependency:Package" is provided by the Java plugin, see http://buschmais.github.io/jqassistant/doc/1.1.2/#dependency.xml, I think the example just should explain that.

**Comment by obfischer** [comment]
I agree.
