### ISSUE TITLE
GraphML plugin neither fails nor does it create a GraphML file

### ISSUE THREAD

**Issue by obfischer** [buschmais/jqassistant#348]
Adding the given example concept `report:PackageDependencies.graphml` from http://buschmais.github.io/jqassistant/doc/1.1.2/#_graphml to the list of rules executed during the build of jQAssistant neither leads to an error nor does it create an GraphML file. 

Please notice that the example concept refers to an other not provided concept called `dependency:Package` which is not present.

**Comment by obfischer** [comment]
Relates to #347

**Comment by obfischer** [comment]
You can find a show case at the branch `showcase-issue-348`. Check this branch out and build it.

**Comment by DirkMahler** [comment]
The graphml plugin was not declared as a dependency of the jQA Maven plugin. Fixed it on the branch, works now as expected.

**Comment by obfischer** [comment]
Thank you. I will remove the branch `showcase-issue-348` from the repository.
