### ISSUE TITLE
Add "Developers" to the Maven plugin

### ISSUE THREAD

**Issue by chrisdutz** [buschmais/jqassistant#358]
Hi,

for my current project I need the developers information in JQA. I've implemented this change and will open a pull request immediately.

Chris

**Comment by obfischer** [comment]
Had a quick look at the pull request. Documentation, unit test and integration tests are missing. I will merge it in the evening or tomorrow and add the missing parts.

**Comment by obfischer** [comment]
I merged the relevant commit by @chrisdutz in `1.1`. Now I will add tests and documentation.

**Comment by obfischer** [comment]
As we have now also all developers in our graph model we should not underestimate the impact of contributors. I will add support for them too.

**Comment by obfischer** [comment]
Now we can support queries for developers and contributors.
