### ISSUE TITLE
Switch rules definition from xml to json ?

### ISSUE THREAD

**Issue by ronanquillevere** [buschmais/jqassistant#367]
This is more a question than a bug.

XML is very verbose and not easy to work with. Is there any particular reason the XML format was chosen vs JSON for the definition of rules ?

JSON would probably ease contributions from the community to build tools on the rule files.

**Comment by obfischer** [comment]
XML was in the first time the simplest choice. It also seems more appropriate if you have the deal with formated text as queries or descriptions. And in Java we have with JAXB a very good tool support. IMHO the fact that we provide a schema helps with editing our configuration files as IDEs can support the editor while writing.

On the other hand we also support embedding of rules and constraints in [Asciidoctor](http://www.asciidoctor.org/). See http://buschmais.github.io/jqassistant/doc/1.1.2/#_asciidoc for details on that.

While JSON is a very easy format it is not easy to deal with it for a human if you have a lot of content as text and Cypher queries with line breaks and if you would like to keep them.

**Comment by ronanquillevere** [comment]
Thx for answering, got your point (IMO jaxb is pretty painful to use but let s not troll here) 

So now we are back to #202  :)

You can close this issue. And continue the good work on this tool :+1:
