### ISSUE TITLE
WAR scanner does not add "Package" label on directories in WEB-INF/classes

### ISSUE THREAD

**Issue by DirkMahler** [buschmais/jqassistant#368]
If a WAR file is scanned containing packages in WEB-INF/classes then the directory structure is built up correctly but the "Package" labels are missing.

**Comment by obfischer** [comment]
Ist das noch was für die 1.1.3?

**Comment by DirkMahler** [comment]
Depends on the required efforts - IMHO should be quite simple to fix so I'll try to include it. 

(BTW: conversation  should be in English ;-) )
