### ISSUE TITLE
Package Scanner does not find any package

### ISSUE THREAD

**Issue by kontext-e** [buschmais/jqassistant#369]
With jQA 1.2.0 and running com.buschmais.jqassistant.scm.cli.Main with args scan -f java:classpath::entities/build/classes/main, the Class Scanner and Artifact Scanner find classes and artifacts, but the Package Scanner does not find any packages.

And why there is a dedicated Package Scanner when also the Class Scanner should be able to determine the packages out of fqn? The Package Scanner seems to guess the packages from file pathes which is error prone when a super directory is given to scan all classes in the hierarchy.

**Comment by kontext-e** [comment]
Just noticed: the Package Scanner DOES find packages, but does not label them correctly as documented. There is no :Java label, so my queries could not find the packages.

**Comment by DirkMahler** [comment]
Directories representing packages (i.e. they were found on a class path) get a "Package" label because there might packages without any Java class in it but resources instead.

**Comment by kontext-e** [comment]
But are packages without any Java class still "Java" packages? Or should only packages Java packages with Java classes in it? And I get wrong packages: "main.de.kontext_e.jqassistant.plugin..."

**Comment by DirkMahler** [comment]
How is your directory structure and which command are you using to scan?

**Comment by kontext-e** [comment]
I use the cli and give e.g. java:classpath::checkstyle/build/classes as argument containing main and test. Yes I _could_ give java:classpath::checkstyle/build/classes/main and java:classpath::checkstyle/build/classes/test but that would double the arguments to maintain. So if there is no chance to change package detection I guess I have to make this.

**Comment by DirkMahler** [comment]
Exactly :-( Detecting the root package would add quite a bit of complex guessing to the plugins.
