### ISSUE TITLE
SonarQube Plugin requires SonarQube 5.0?

### ISSUE THREAD

**Issue by haggard1979** [buschmais/jqassistant#388]
Hello,

we're trying to use the jqassistant SonarQube-Plugin with our SonarQube server (Version 4.5.7).

According to jqassistant Releasenotes for version 1.1.3 (http://buschmais.github.io/jqassistant/doc/1.1.3/release-notes.html) this should be possible:

> Migrated jQAssistant SonarQube plugins to support SonarQube 4.x/5.1.x (Note: compatibility with 3.x has been dropped)

However we're seeing the following Exception in our SonarQube Logfile:

> org.sonar.api.utils.MessageException: Plugin jqassistantprojectrules needs a more recent version of SonarQube than 4.5.7. At least 5.0 is expected

We're using
jqassistant.sonar.plugin-1.1.3.jar (plugin) and
jqassistant.sonar.projectrules-1.1.3.jar (extension)

Unfortunatly upgrading SonarQube isn't an option for us right now. 

Regards,
Tom

**Comment by DirkMahler** [comment]
We will verify this.
