### ISSUE TITLE
Create non-interactive server task

### ISSUE THREAD

**Issue by sjahreis** [buschmais/jqassistant#393]
Hi there,

As we are executing the server within a docker container on openshift, we don't have a *stdin* and therefore the call to `System.in.read` (ServerTask:38) instantly returns -1 and the server shuts down.

Adding a non-interactive task would solve this issue. Is that possible?

Thanks

**Comment by DirkMahler** [comment]
There has already been a PR for the CLI (https://github.com/buschmais/jqassistant/pull/385/files), shouldn't be a big deal to integrate it. I'm not sure if we should also consider adding a similar option to the Maven plugin, IMHO it makes less sense there.

**Comment by sjahreis** [comment]
Cool, thanks!

**Comment by DirkMahler** [comment]
The PR has been integrated, the server task now provides a "-daemon" option.
